### ISSUE TITLE
UI does not load the main screen after login

### ISSUE THREAD

**Issue by neelimamukiri** [contiv/contiv-ui#282]
<img width="1148" alt="screen shot 2017-02-17 at 10 25 25 am" src="https://cloud.githubusercontent.com/assets/15221658/23078635/4f1b25d0-f4fe-11e6-8b5a-9803568f07d3.png">

This is a k8s setup with UI being accessed from a Chrome browser.
Login seems to work fine, but the UI is not getting redirected. Token is valid, network are being pulled correctly. 

Vishal was looking at it, so assigning to him. The user trying out the issue will try to get a repro.

**Comment by neelimamukiri** [comment]
https://github.com/contiv/ccn/issues/216 may be related.

**Comment by rashers** [comment]
I have created a centos7 vm locally on my laptop and installed kubenetes and contiv using same method and have same issue with admin/admin returning to login screen.  
I have tried beta1, 2 and 3.   
I have tried using chrome, safari and firefox and hit same issue.  
I have tried to access from macbook and windows 10 vm using Edge.    
I have tried with docker 1.11.2 and 12.5 all give same results.    
I have also tried to install contiv on an ubuntu with same results.  
I have also installed on a vps available at https://164.132.97.168:10000 and get same result.

I am following this process to reproduce

On fresh Centos7 minimal install
install docker kubelet kubeadm kubectl kubernetes-cni
start services
kubeadm init --service-cidr 10.254.0.0/16
download contiv tgz and untar
from contiv dir  install/k8s/install -n masterip
try to login at https://masterip:10000
accepts admin/admin but returns to login page,  using developer i can see token 

i have noticed in developer tools if i login as admin/admin i do not see anything saved under local storage,  if i login as ops/ops i see the following set
authToken
loginTime       
lastAccessTime  
username

When logging in as ops/ops I do not get the login page refreshing but get an unauthorized page as no permissions have been set for ops user.

**Comment by shampur** [comment]
@rashers Can you provide us the token that you got in response after you login as admin/admin.

**Comment by rashers** [comment]
supplied this via slack

**Comment by angry-tony** [comment]
hello, all

i am facing same error to login contiv-ui.
is it solved??

**Comment by rashers** [comment]
no,  I dont think anyone is looking at it as it was only me and they could not reproduce.  I have given up and looking for another solution

**Comment by dseevr** [comment]
Hi everyone,

Could the people facing this issue please reply with:

```
OS version:
Browser name and version:
List of active plugins:
Contiv version:
```

We are unable to reproduce this issue so it's proving difficult to come up with a fix.  Once we can reproduce it, we will be able to provide a fix.  I am very sorry for the inconvenience.  I really want to get to the bottom of this issue ASAP.

@rashers I accidentally deleted your last comment with a wild click 😞 Sorry!

**Comment by vishal-j** [comment]
We made a fix for an issue where one would see this symptom if browser and server clock were not in synch. I am not sure if @angry-tony is hitting the same issue as @rashers although symptom is the same.

@dseevr, can we pick the latest bits from contiv-ui in auth_proxy and @angry-tony can try it?

**Comment by angry-tony** [comment]
Hello all

@vishal-j It's same..

i did this below

'''
OS version: CentOS 7
Browser name and version: chrome, safari and firefox latest
List of active plugins: contiv-1.0.0-beta.3.tgz
Contiv version: contiv-1.0.0-beta.3.tgz
'''
'''
[root@k8s-controller-01 ~]# kubeadm init --api-advertise-addresses=192.168.147.20 --skip-preflight-checks=true --use-kubernetes-version v1.4.7 --service-cidr 10.254.0.0/16

[root@k8s-controller-01 ~]# curl -L -O https://github.com/contiv/install/releases/download/1.0.0-beta.3/contiv-1.0.0-beta.3.tgz; \
tar xf contiv-1.0.0-beta.3.tgz; \
cd contiv-1.0.0-beta.3

[root@k8s-controller-01 contiv-1.0.0-beta.3]# sudo ./install/k8s/install.sh -n 192.168.147.20 -v eth4

try to login at https://192.168.147.20:10000
'''

**Comment by dseevr** [comment]
@angry-tony Sorry, that was meant to be "browser plugins".  I updated the post.

When you say latest Safari, are you running 10.11 (MacOS Sierra)?

**Comment by angry-tony** [comment]
@dseevr   yes. i am running 10.11

**Comment by dseevr** [comment]
@angry-tony any browser plugins active?

**Comment by angry-tony** [comment]
@dseevr  what is browser plugins??
I have tried using chrome and firefox on Centos 7 and explorer  on windows 10.
chrome and firefor on winodws 10..

all is the same.

**Comment by dseevr** [comment]
@angry-tony a browser plugin is something like Adblock Plus, Ghostery, uBlock Origin, NoScript, and so on

A lot of the manipulate the DOM, hook DOM events, block assets from loading, prevent Javascript from running properly, etc. which is why I'm curious if any are involved

**Comment by rashers** [comment]
i am the same as @angry-tony i have tried

chrome / safari on mac
explorer / edge / firefox on windows 10
chrome / firefox on ubuntu

all had same issue.  I can setup a vps with internet access and let you have access to help debug this if that helps.

**Comment by chungewa** [comment]
My test bed is ACI multiPod + Contiv + Docker Swarm, after install, all the data plane is ok! But from Chrome/IE/Safari, it just stucks there after input the default username/pwd. 
**Any other information should i upload here?**

**Comment by chungewa** [comment]
OS version: Contiv based on newest Centos 7
Browser name and version:  Chrome/IE/Safari
List of browser plugins: webex/postman
Contiv version: contiv-full-1.0.0-beta.3.tgz

**Comment by chungewa** [comment]
Actually, i dont know its good or bad news:
This time i try the Contiv UI from the Swarm Master its self(https://master-ip:10000), i can login,
BUT, the new issue is, the UI take me again into firstrun wizard, even in my environment, all configuration has beed done from netctl CLI days before.
And, in the wizard, it also didnt pickup my already-done-configuration, just like its a fresh one.

**Comment by dseevr** [comment]
@chungewa Thanks for the report.  Just to confirm... you are able to login successfully on the master IP but not on the others?

**Comment by chungewa** [comment]
@dseevr  
On my Swarm Master host itself, a physical server with CentOS, using the firefox default browser, i can login Contiv UI(https://master-ip:10000), this master-ip is also the control ( in cfg.yml ) interface ip . 
But from any other client, i can ssh into master, but cannt login Contiv UI(https://master-ip:10000), by safari,chrome,IE,firefox.  
Just Now, i try the  https://master-ip:10000 from my Contiv install host,another physical server with CentOS, i found i can login too.

**Comment by angry-tony** [comment]
@dseevr hello!! I have one question.. where can i find auth-proxy's log files to check auth-proxy status or error??

**Comment by dseevr** [comment]
@angry-tony auth_proxy writes its logs to stdout and stderr if you're running it as a binary.  If you're running it via Docker, you can `docker logs -f <container_id>` to see what's going on.

**Comment by angry-tony** [comment]
it's working on the version of "Fixes login issue #290"
[Fixes login issue #290](https://github.com/contiv/contiv-ui/pull/290)

**Comment by dseevr** [comment]
@angry-tony Awesome!  Thanks for the confirmation

We're putting out a beta4 release soon (next few days) which will include this change and will be easily testable using the Contiv installer.  I'll post an update here when it's available.

**Comment by rhim** [comment]
@angry-tony beta.4 release is out. Please take a look and see if that fixes the issue.

**Comment by rashers** [comment]
I tried Beta 5 and login works for me

**Comment by dseevr** [comment]
@rashers thanks for the confirmation 😄

**Comment by rhim** [comment]
:+1:
