### ISSUE TITLE
First run wizard reads the partial ACI configuration

### ISSUE THREAD

**Issue by neelimamukiri** [contiv/contiv-ui#288]
<img width="336" alt="screen shot 2017-03-14 at 2 04 03 pm" src="https://cloud.githubusercontent.com/assets/15221658/23922325/1c2b87d0-08bf-11e7-955b-09fd32543d44.png">
<img width="388" alt="screen shot 2017-03-14 at 2 03 55 pm" src="https://cloud.githubusercontent.com/assets/15221658/23922324/1c2a17e2-08bf-11e7-9d7a-8a1f9f1c819b.png">

**Comment by neelimamukiri** [comment]
The ACI settings should be loaded as well. Also we need a way to skip the first run wizard.

**Comment by vishal-j** [comment]
@neelimamukiri I am unable to reproduce it.
